name: gwn39
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - blas=1.0=openblas
  - blosc=1.21.6=h7dd00d9_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.6=hc919400_0
  - c-blosc2=2.15.2=h9cbb436_1
  - ca-certificates=2025.12.2=hca03da5_0
  - certifi=2025.10.5=py39hca03da5_0
  - hdf5=1.14.3=nompi_ha698983_109
  - krb5=1.21.3=h237132a_0
  - libaec=1.1.4=h51d1e36_0
  - libcurl=8.17.0=hdece5d2_1
  - libcxx=20.1.8=hd7fd590_1
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libffi=3.4.4=hca03da5_1
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libsqlite=3.51.1=h1b79a29_1
  - libssh2=1.11.1=h1590b86_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.8=h4a912ad_0
  - lz4-c=1.10.0=h286801f_1
  - ncurses=6.5=hee39554_0
  - numexpr=2.10.2=py39h82972a1_0
  - numpy=1.23.5=py39h1398885_0
  - numpy-base=1.23.5=py39h90707a3_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pip=25.3=pyhc872135_0
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pytables=3.9.2=py39h08360a6_3
  - python=3.9.20=h9e33284_1_cpython
  - python_abi=3.9=8_cp39
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py39hca03da5_0
  - snappy=1.2.2=hada39a4_1
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py39hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zlib-ng=2.2.5=h3470cca_1
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - appnope==0.1.4
      - argparse==1.4.0
      - asttokens==3.0.1
      - comm==0.2.3
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - durbango==0.23
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastprogress==1.0.3
      - fonttools==4.60.1
      - funcy==2.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - ipykernel==6.31.0
      - ipython==8.18.1
      - jedi==0.19.2
      - joblib==1.5.2
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.7
      - matplotlib==3.9.4
      - matplotlib-inline==0.2.1
      - nest-asyncio==1.6.0
      - pandas==1.5.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.4.0
      - pluggy==1.6.0
      - prompt-toolkit==3.0.52
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py3nvml==0.2.7
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==27.1.0
      - scikit-learn==1.6.1
      - scipy==1.9.3
      - six==1.17.0
      - stack-data==0.6.3
      - threadpoolctl==3.6.0
      - tomli==2.3.0
      - torch==1.10.2
      - torchaudio==0.10.2
      - torchvision==0.11.3
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - wcwidth==0.2.14
      - xmltodict==1.0.2
      - zipp==3.23.0
prefix: /opt/anaconda3/envs/gwn39
